
################################################################################
# Core module resources
################################################################################
SET(MOD_CORE_MODULECLASS ITK_GENERATEDModule)

SET(MOD_CORE_SOURCES
    ${MOD_DIR}/processors/itk_AnisotropicSmoothing/curvatureanisotropicdiffusionimagefilter.cpp 
    ${MOD_DIR}/processors/itk_AnisotropicSmoothing/gradientanisotropicdiffusionimagefilter.cpp 
    ${MOD_DIR}/processors/itk_AnisotropicSmoothing/vectorcurvatureanisotropicdiffusionimagefilter.cpp 
    ${MOD_DIR}/processors/itk_AnisotropicSmoothing/vectorgradientanisotropicdiffusionimagefilter.cpp 
    ${MOD_DIR}/processors/itk_AntiAlias/antialiasbinaryimagefilter.cpp 
    ${MOD_DIR}/processors/itk_BinaryMathematicalMorphology/binarydilateimagefilter.cpp 
    ${MOD_DIR}/processors/itk_BinaryMathematicalMorphology/binaryerodeimagefilter.cpp 
    ${MOD_DIR}/processors/itk_BinaryMathematicalMorphology/binarymorphologicalclosingimagefilter.cpp 
    ${MOD_DIR}/processors/itk_BinaryMathematicalMorphology/binarymorphologicalopeningimagefilter.cpp 
    ${MOD_DIR}/processors/itk_BinaryMathematicalMorphology/binarypruningimagefilter.cpp 
    ${MOD_DIR}/processors/itk_BinaryMathematicalMorphology/dilateobjectmorphologyimagefilter.cpp 
    ${MOD_DIR}/processors/itk_BinaryMathematicalMorphology/erodeobjectmorphologyimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ConnectedComponents/connectedcomponentimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ConnectedComponents/hardconnectedcomponentimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ConnectedComponents/relabelcomponentimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ConnectedComponents/scalarconnectedcomponentimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ConnectedComponents/thresholdmaximumconnectedcomponentsimagefilter.cpp 
    ${MOD_DIR}/processors/itk_CurvatureFlow/curvatureflowimagefilter.cpp 
    ${MOD_DIR}/processors/itk_CurvatureFlow/minmaxcurvatureflowimagefilter.cpp 
    ${MOD_DIR}/processors/itk_DistanceMap/contourdirectedmeandistanceimagefilter.cpp 
    ${MOD_DIR}/processors/itk_DistanceMap/contourmeandistanceimagefilter.cpp 
    ${MOD_DIR}/processors/itk_DistanceMap/danielssondistancemapimagefilter.cpp 
    ${MOD_DIR}/processors/itk_DistanceMap/directedhausdorffdistanceimagefilter.cpp 
    ${MOD_DIR}/processors/itk_DistanceMap/hausdorffdistanceimagefilter.cpp 
    ${MOD_DIR}/processors/itk_DistanceMap/signeddanielssondistancemapimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageCompare/absolutevaluedifferenceimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageCompare/checkerboardimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageCompare/similarityindeximagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageCompare/squareddifferenceimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageFeature/cannyedgedetectionimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageFeature/derivativeimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageFeature/laplacianimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageFeature/laplacianrecursivegaussianimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageFeature/laplaciansharpeningimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageFeature/simplecontourextractorimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageFeature/sobeledgedetectionimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageFeature/zerocrossingbasededgedetectionimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageFeature/zerocrossingimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageFusion/labeloverlayimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageFusion/labeltorgbimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageGradient/gradientimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageGradient/gradientmagnitudeimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageGradient/gradientmagnituderecursivegaussianimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageGradient/gradientrecursivegaussianimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageGradient/vectorgradientmagnitudeimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/absimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/acosimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/addimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/andimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/asinimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/atan2imagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/atanimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/binarymagnitudeimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/boundedreciprocalimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/constrainedvalueadditionimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/constrainedvaluedifferenceimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/cosimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/divideimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/edgepotentialimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/expimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/expnegativeimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/intensitywindowingimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/invertintensityimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/log10imagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/logimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/maskimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/maximumimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/minimumimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/modulusimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/multiplyimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/notimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/orimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/rescaleintensityimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/shiftscaleimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/sigmoidimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/sinimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/sqrtimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/squareimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/subtractimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/tanimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/ternaryaddimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/ternarymagnitudeimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/ternarymagnitudesquaredimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/weightedaddimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageIntensity/xorimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageLabel/binarycontourimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageLabel/labelcontourimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageStatistics/accumulateimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageStatistics/adaptivehistogramequalizationimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageStatistics/getaveragesliceimagefilter.cpp 
    ${MOD_DIR}/processors/itk_ImageStatistics/minimummaximumimagefilter.cpp 
    ${MOD_DIR}/processors/itk_LabelVoting/binarymedianimagefilter.cpp 
    ${MOD_DIR}/processors/itk_LabelVoting/labelvotingimagefilter.cpp 
    ${MOD_DIR}/processors/itk_LabelVoting/votingbinaryholefillingimagefilter.cpp 
    ${MOD_DIR}/processors/itk_LabelVoting/votingbinaryiterativeholefillingimagefilter.cpp 
    ${MOD_DIR}/processors/itk_LevelSets/curveslevelsetimagefilter.cpp 
    ${MOD_DIR}/processors/itk_LevelSets/geodesicactivecontourlevelsetimagefilter.cpp 
    ${MOD_DIR}/processors/itk_LevelSets/geodesicactivecontourshapepriorlevelsetimagefilter.cpp 
    ${MOD_DIR}/processors/itk_LevelSets/narrowbandcurveslevelsetimagefilter.cpp 
    ${MOD_DIR}/processors/itk_LevelSets/narrowbandthresholdsegmentationlevelsetimagefilter.cpp 
    ${MOD_DIR}/processors/itk_LevelSets/shapedetectionlevelsetimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/basicdilateimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/basicerodeimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/blacktophatimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/closingbyreconstructionimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/doublethresholdimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscaleconnectedclosingimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscaleconnectedopeningimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscaledilateimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscaleerodeimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalefillholeimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalefunctiondilateimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalefunctionerodeimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalegeodesicdilateimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalegeodesicerodeimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalegrindpeakimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalemorphologicalclosingimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalemorphologicalopeningimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/hconcaveimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/hconveximagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/hmaximaimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/hminimaimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/morphologicalgradientimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/movinghistogramdilateimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/movinghistogramerodeimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/movinghistogrammorphologicalgradientimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/openingbyreconstructionimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/reconstructionbydilationimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/reconstructionbyerosionimagefilter.cpp 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/whitetophatimagefilter.cpp 
    ${MOD_DIR}/processors/itk_RegionGrowing/confidenceconnectedimagefilter.cpp 
    ${MOD_DIR}/processors/itk_RegionGrowing/connectedthresholdimagefilter.cpp 
    ${MOD_DIR}/processors/itk_RegionGrowing/isolatedconnectedimagefilter.cpp 
    ${MOD_DIR}/processors/itk_RegionGrowing/neighborhoodconnectedimagefilter.cpp 
    ${MOD_DIR}/processors/itk_Smoothing/binomialblurimagefilter.cpp 
    ${MOD_DIR}/processors/itk_Smoothing/discretegaussianimagefilter.cpp 
    ${MOD_DIR}/processors/itk_Smoothing/meanimagefilter.cpp 
    ${MOD_DIR}/processors/itk_Smoothing/medianimagefilter.cpp 
    ${MOD_DIR}/processors/itk_Smoothing/recursivegaussianimagefilter.cpp 
    ${MOD_DIR}/processors/itk_Smoothing/smoothingrecursivegaussianimagefilter.cpp 
    ${MOD_DIR}/processors/itk_Thresholding/binarythresholdimagefilter.cpp 
    ${MOD_DIR}/processors/itk_Thresholding/otsumultiplethresholdsimagefilter.cpp 
    ${MOD_DIR}/processors/itk_Thresholding/otsuthresholdimagefilter.cpp 
    ${MOD_DIR}/processors/itk_Thresholding/thresholdimagefilter.cpp 
    ${MOD_DIR}/processors/itk_Watersheds/isolatedwatershedimagefilter.cpp 

)

SET(MOD_CORE_HEADERS
    ${MOD_DIR}/processors/itk_AnisotropicSmoothing/curvatureanisotropicdiffusionimagefilter.h 
    ${MOD_DIR}/processors/itk_AnisotropicSmoothing/gradientanisotropicdiffusionimagefilter.h 
    ${MOD_DIR}/processors/itk_AnisotropicSmoothing/vectorcurvatureanisotropicdiffusionimagefilter.h 
    ${MOD_DIR}/processors/itk_AnisotropicSmoothing/vectorgradientanisotropicdiffusionimagefilter.h 
    ${MOD_DIR}/processors/itk_AntiAlias/antialiasbinaryimagefilter.h 
    ${MOD_DIR}/processors/itk_BinaryMathematicalMorphology/binarydilateimagefilter.h 
    ${MOD_DIR}/processors/itk_BinaryMathematicalMorphology/binaryerodeimagefilter.h 
    ${MOD_DIR}/processors/itk_BinaryMathematicalMorphology/binarymorphologicalclosingimagefilter.h 
    ${MOD_DIR}/processors/itk_BinaryMathematicalMorphology/binarymorphologicalopeningimagefilter.h 
    ${MOD_DIR}/processors/itk_BinaryMathematicalMorphology/binarypruningimagefilter.h 
    ${MOD_DIR}/processors/itk_BinaryMathematicalMorphology/dilateobjectmorphologyimagefilter.h 
    ${MOD_DIR}/processors/itk_BinaryMathematicalMorphology/erodeobjectmorphologyimagefilter.h 
    ${MOD_DIR}/processors/itk_ConnectedComponents/connectedcomponentimagefilter.h 
    ${MOD_DIR}/processors/itk_ConnectedComponents/hardconnectedcomponentimagefilter.h 
    ${MOD_DIR}/processors/itk_ConnectedComponents/relabelcomponentimagefilter.h 
    ${MOD_DIR}/processors/itk_ConnectedComponents/scalarconnectedcomponentimagefilter.h 
    ${MOD_DIR}/processors/itk_ConnectedComponents/thresholdmaximumconnectedcomponentsimagefilter.h 
    ${MOD_DIR}/processors/itk_CurvatureFlow/curvatureflowimagefilter.h 
    ${MOD_DIR}/processors/itk_CurvatureFlow/minmaxcurvatureflowimagefilter.h 
    ${MOD_DIR}/processors/itk_DistanceMap/contourdirectedmeandistanceimagefilter.h 
    ${MOD_DIR}/processors/itk_DistanceMap/contourmeandistanceimagefilter.h 
    ${MOD_DIR}/processors/itk_DistanceMap/danielssondistancemapimagefilter.h 
    ${MOD_DIR}/processors/itk_DistanceMap/directedhausdorffdistanceimagefilter.h 
    ${MOD_DIR}/processors/itk_DistanceMap/hausdorffdistanceimagefilter.h 
    ${MOD_DIR}/processors/itk_DistanceMap/signeddanielssondistancemapimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageCompare/absolutevaluedifferenceimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageCompare/checkerboardimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageCompare/similarityindeximagefilter.h 
    ${MOD_DIR}/processors/itk_ImageCompare/squareddifferenceimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageFeature/cannyedgedetectionimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageFeature/derivativeimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageFeature/laplacianimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageFeature/laplacianrecursivegaussianimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageFeature/laplaciansharpeningimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageFeature/simplecontourextractorimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageFeature/sobeledgedetectionimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageFeature/zerocrossingbasededgedetectionimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageFeature/zerocrossingimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageFusion/labeloverlayimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageFusion/labeltorgbimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageGradient/gradientimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageGradient/gradientmagnitudeimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageGradient/gradientmagnituderecursivegaussianimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageGradient/gradientrecursivegaussianimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageGradient/vectorgradientmagnitudeimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/absimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/acosimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/addimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/andimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/asinimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/atan2imagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/atanimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/binarymagnitudeimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/boundedreciprocalimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/constrainedvalueadditionimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/constrainedvaluedifferenceimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/cosimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/divideimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/edgepotentialimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/expimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/expnegativeimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/intensitywindowingimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/invertintensityimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/log10imagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/logimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/maskimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/maximumimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/minimumimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/modulusimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/multiplyimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/notimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/orimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/rescaleintensityimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/shiftscaleimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/sigmoidimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/sinimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/sqrtimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/squareimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/subtractimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/tanimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/ternaryaddimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/ternarymagnitudeimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/ternarymagnitudesquaredimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/weightedaddimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageIntensity/xorimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageLabel/binarycontourimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageLabel/labelcontourimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageStatistics/accumulateimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageStatistics/adaptivehistogramequalizationimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageStatistics/getaveragesliceimagefilter.h 
    ${MOD_DIR}/processors/itk_ImageStatistics/minimummaximumimagefilter.h 
    ${MOD_DIR}/processors/itk_LabelVoting/binarymedianimagefilter.h 
    ${MOD_DIR}/processors/itk_LabelVoting/labelvotingimagefilter.h 
    ${MOD_DIR}/processors/itk_LabelVoting/votingbinaryholefillingimagefilter.h 
    ${MOD_DIR}/processors/itk_LabelVoting/votingbinaryiterativeholefillingimagefilter.h 
    ${MOD_DIR}/processors/itk_LevelSets/curveslevelsetimagefilter.h 
    ${MOD_DIR}/processors/itk_LevelSets/geodesicactivecontourlevelsetimagefilter.h 
    ${MOD_DIR}/processors/itk_LevelSets/geodesicactivecontourshapepriorlevelsetimagefilter.h 
    ${MOD_DIR}/processors/itk_LevelSets/narrowbandcurveslevelsetimagefilter.h 
    ${MOD_DIR}/processors/itk_LevelSets/narrowbandthresholdsegmentationlevelsetimagefilter.h 
    ${MOD_DIR}/processors/itk_LevelSets/shapedetectionlevelsetimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/basicdilateimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/basicerodeimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/blacktophatimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/closingbyreconstructionimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/doublethresholdimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscaleconnectedclosingimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscaleconnectedopeningimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscaledilateimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscaleerodeimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalefillholeimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalefunctiondilateimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalefunctionerodeimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalegeodesicdilateimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalegeodesicerodeimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalegrindpeakimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalemorphologicalclosingimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/grayscalemorphologicalopeningimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/hconcaveimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/hconveximagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/hmaximaimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/hminimaimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/morphologicalgradientimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/movinghistogramdilateimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/movinghistogramerodeimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/movinghistogrammorphologicalgradientimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/openingbyreconstructionimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/reconstructionbydilationimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/reconstructionbyerosionimagefilter.h 
    ${MOD_DIR}/processors/itk_MathematicalMorphology/whitetophatimagefilter.h 
    ${MOD_DIR}/processors/itk_RegionGrowing/confidenceconnectedimagefilter.h 
    ${MOD_DIR}/processors/itk_RegionGrowing/connectedthresholdimagefilter.h 
    ${MOD_DIR}/processors/itk_RegionGrowing/isolatedconnectedimagefilter.h 
    ${MOD_DIR}/processors/itk_RegionGrowing/neighborhoodconnectedimagefilter.h 
    ${MOD_DIR}/processors/itk_Smoothing/binomialblurimagefilter.h 
    ${MOD_DIR}/processors/itk_Smoothing/discretegaussianimagefilter.h 
    ${MOD_DIR}/processors/itk_Smoothing/meanimagefilter.h 
    ${MOD_DIR}/processors/itk_Smoothing/medianimagefilter.h 
    ${MOD_DIR}/processors/itk_Smoothing/recursivegaussianimagefilter.h 
    ${MOD_DIR}/processors/itk_Smoothing/smoothingrecursivegaussianimagefilter.h 
    ${MOD_DIR}/processors/itk_Thresholding/binarythresholdimagefilter.h 
    ${MOD_DIR}/processors/itk_Thresholding/otsumultiplethresholdsimagefilter.h 
    ${MOD_DIR}/processors/itk_Thresholding/otsuthresholdimagefilter.h 
    ${MOD_DIR}/processors/itk_Thresholding/thresholdimagefilter.h 
    ${MOD_DIR}/processors/itk_Watersheds/isolatedwatershedimagefilter.h 

)
