@ECHO off

REM adapted from 
REM http://svn.haxx.se/users/archive-2006-02/0473.shtml
REM (jms)

REM  I hate Windows bat. files.  CN
REM  Found this method of executing the `svnversion` program and storing
REM  the returned value in a environment variable.
REM    http://svn.haxx.se/users/archive-2004-09/0502.shtml
REM
REM  Version 1.3.0 of `svnversion` doesn't require a path, but it is left
REM  for compatability with previous versions of the program

FOR /F "usebackq" %%s IN (`ext\svnversion\svnversion .`) DO @SET REV=%%s
REM  Now that we have the revision string, lets build a class.

REM  Be sure to tell anyone who looks at this file it was generated by
REM  a program and not hand writen.  Do not commit the output of this
REM  batch script to your repository!  Just the script.

echo // auto-generated by svnversion.bat  > %2
rem if [ -z "$SVN_REV" ]; then
rem   echo "// svnversion binary not found or this not a working copy" >> $VERSION_H
rem   echo "#undef VRN_SVN_REVISON" >> $VERSION_H
rem else
  echo // extracted from working copy at %1 >> %2 
  echo #undef VRN_SVN_REVISON >> %2 
  echo #define VRN_SVN_REVISON "%REV%" >> %2 
rem fi
