#!/bin/sh

ROOT=$1
VERSION_H=$2
VERSION_H_TMP=$2.tmp
SVN_REV=`svnversion -n $ROOT 2> /dev/null`
DATE=`date `

echo -e "// auto-generated by svnversion.sh\n" > $VERSION_H_TMP
if [ -z "$SVN_REV" ]; then
  echo "// svnversion binary not found or this not a working copy" >> $VERSION_H_TMP
  echo "#undef VRN_SVN_REVISON" >> $VERSION_H_TMP
else
  echo "// extracted from working copy at $ROOT" >> $VERSION_H_TMP
  echo "#define VRN_SVN_REVISON \"$SVN_REV\"" >> $VERSION_H_TMP
fi

cmp --silent $VERSION_H $VERSION_H_TMP 2> /dev/null
if [ $? == 0 ]; then
  rm -f $VERSION_H_TMP
else
  mv $VERSION_H_TMP $VERSION_H
fi
