
set(VOREEN_VERSION 4.3)
set(VOREEN_REPO_URL https://github.com/bilgili/Voreen.git)
set(VOREEN_REPO_TAG bbp)
set(VOREEN_DEPENDS DevIL)
set(VOREEN_NOPACKAGE ON)
set(VOREEN_NOTEST ON)
set(VOREEN_OPTIONAL ON)
set(VOREEN_CMAKE_ARGS -DVRN_PRECOMPILED_HEADER=false -DBoost_NO_SYSTEM_PATHS=true -DVRN_ADD_INSTALL_TARGET=true)


if(CI_BUILD_COMMIT)
  set(VOREEN_REPO_TAG ${CI_BUILD_COMMIT})
else()
  set(VOREEN_REPO_TAG master)
endif()
set(VOREEN_FORCE_BUILD ON)
set(VOREEN_SOURCE ${CMAKE_SOURCE_DIR})
